default:
  url: https://endoflife.date
  alert:
    month: 12
plugins: 
  slack:
    webhook_url: https://hooks.slack.com/services/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
    attachments: 
      - author: 
          name: End Of Life Notifier
          link: https://cloudposse.com/wp-content/uploads/sites/29/2018/02/small-cute-robot-square.png
          icon: https://pilot.dolmen-tech.com/sites/all/themes/pilot/favicon.ico
        color: good
        thumb_url: https://lh3.googleusercontent.com/-q66v8AqIhDA/X47v0k1v7eI/AAAAAAAAINc/Ey0rl1JuRRwGOnVymewkV_tF9aAtXeTKACLcBGAsYHQ/s1600/Cool%2BMonkey%2BLogo%2BDesign.jpg
    user_name: Robot
    icon_emoji: white_check_mark


products:
  - name: "bootstrap"
    version: 4.x

  - name: "drupal"
    version: 7

  - name: "go"
    version: 1.14

  - name: "java"
    version: 11

  - name: "kubernetes"
    version: 1.23

  - name: "mysql"
    version: 5.7
    impactedProduct:
      - "all"

  - name: "php"
    version: 7.4

  - name: "spring-framework"
    version: 5.3

  - name: "symfony"
    version: 3.3

  #- name: "vue"
  #  version: 2.6.0
  #  custom_url:
  #    url: https://github.com/
  #    method: GET
  #    body: ""
