includes:
  - plugins/slack/config.yaml
  
default:
  url: https://endoflife.date
  alert:
    month: 12
products:
  - name: "bootstrap"
    version: 4.0.0

  - name: "drupal"
    version: 7

  - name: "go"
    version: 1.17

  - name: "java"
    version: 11


